[package]
name = "Crowndfounding_on_NEAR"
version = "1.0.0"
authors = ["ISSET LLC <info@uht-sport.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0-pre.2"
near-contract-standards = "4.0.0-pre.2"
